### ISSUE TITLE
The charset=utf8 is not a valid data URI scheme

### ISSUE THREAD

**Issue by pablonoel** [waldemarfm/sass-svg-uri#3]
Source: https://tools.ietf.org/html/rfc2397

This:
@return url("data:image/svg+xml;charset=utf8,#{$encoded}");

Should be:
@return url("data:image/svg+xml;utf8,#{$encoded}")

**Comment by waldemarfm** [comment]
Actually I've read it doesn't even need the `utf8` part. Read more here https://codepen.io/tigt/post/optimizing-svgs-in-data-uris

`1.0.2` should take care of this. Closing issue.
